import type{Config}from"./types.js";
import{spawn}from"node:child_process";
export async function askLLM(c:Config,p:string,o:any={}):Promise<string>{if(c.provider==="deepseek")return askDeepSeek(c,p,o);if(c.provider==="claude")return askClaude(c,p,o);const b:any={model:c.model,messages:[{role:"user",content:p}],stream:false,think:o.think??false,options:{temperature:o.temperature??c.temperature,top_p:.9,top_k:20,repeat_penalty:1.05,num_ctx:o.num_ctx??c.numCtx}};if(o.json)b.format="json";const r=await fetch(c.ollamaUrl,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)}),raw=await r.text();if(!r.ok)throw Error(`Ollama HTTP ${r.status}: ${raw}`);let d:any;try{d=JSON.parse(raw)}catch{throw Error(`Invalid Ollama response JSON:\n${raw}`)}if(d.error)throw Error(d.error);const content=d.message?.content?.trim()??"";if(!content)throw Error(`Ollama returned empty content.\n${raw}`);return content}
async function askDeepSeek(c:Config,p:string,o:any={}):Promise<string>{if(!c.deepseek.apiKey)throw Error("Chưa cấu hình DeepSeek API key. Vào Cài đặt để nhập.");const b:any={model:c.deepseek.model,messages:[{role:"user",content:p}],stream:false,temperature:o.temperature??c.temperature,max_tokens:16384,reasoning_effort:"none"};if(o.json)b.response_format={type:"json_object"};const r=await fetch("https://api.deepseek.com/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${c.deepseek.apiKey}`},body:JSON.stringify(b)}),raw=await r.text();if(!r.ok)throw Error(`DeepSeek HTTP ${r.status}: ${raw}`);let d:any;try{d=JSON.parse(raw)}catch{throw Error(`Invalid DeepSeek response JSON:\n${raw}`)}if(d.error)throw Error(typeof d.error==="string"?d.error:JSON.stringify(d.error));if(d.choices?.[0]?.finish_reason==="length"){const m0=d.choices[0].message??{},txt=String(m0.content??""),rc=String(m0.reasoning_content??"");throw Error(`DeepSeek response truncated (max_tokens reached). usage=${JSON.stringify(d.usage??{})} contentChars=${txt.length} reasoningChars=${rc.length} tail=${JSON.stringify(txt.slice(-400))}`)}const content=d.choices?.[0]?.message?.content?.trim()??"";if(!content)throw Error(`DeepSeek returned empty content.\n${raw}`);return content}
async function askClaude(c:Config,p:string,o:any={}):Promise<string>{const args=["-p","--output-format","text","--tools","","--safe-mode","--system-prompt","You output exactly what is requested, nothing else."];if(c.claude.model)args.push("--model",c.claude.model);const content=await new Promise<string>((resolve,reject)=>{const proc=spawn("claude",args,{stdio:["pipe","pipe","pipe"]});let out="",err="";proc.stdout.on("data",d=>out+=d);proc.stderr.on("data",d=>err+=d);proc.on("error",e=>reject(Error(`Không chạy được lệnh "claude". Cần cài Claude Code CLI và đăng nhập trước. (${e.message})`)));proc.on("close",code=>code===0?resolve(out):reject(Error(`Claude CLI thoát với mã ${code}: ${(err||out).trim().slice(0,500)}`)));proc.stdin.write(p);proc.stdin.end()});const trimmed=content.trim();if(!trimmed)throw Error("Claude CLI trả về nội dung rỗng.");return trimmed}
export function extractJSON<T=any>(raw:string):T|null{const s=raw.trim().replace(/^```json\s*/i,"").replace(/^```\s*/i,"").replace(/\s*```$/i,"");try{return JSON.parse(s)}catch{}for(const[a,b]of[[s.indexOf("{"),s.lastIndexOf("}")],[s.indexOf("["),s.lastIndexOf("]")]])if(a>=0&&b>a)try{return JSON.parse(s.slice(a,b+1))}catch{}return null}
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function backoffMs(attempt:number,err:string){const throttled=/\b(429|529|503)\b|rate.?limit|too many requests|overloaded/i.test(err);const base=throttled?5000:800;
// Trần thời gian chờ: với 10 lượt thử, 800*2^9 là hơn 6 phút nằm không giữa hai lượt.
return Math.round(Math.min(base*2**(attempt-1),throttled?60000:15000)*(1+Math.random()*.3))}
// c.maxRetries (ô Cài đặt, mặc định 3) cộng/trừ đều vào mọi chặng chứ không đè lên
// con số của từng chặng: các bước phụ (review, continuity) cố tình chỉ thử 2 lượt, để
// nguyên mặc định thì chúng vẫn là 2. Nhiệt độ chạy vòng [t,.2,.1] chứ không dừng hẳn
// ở .1: từ lượt 4 trở đi mà cứ .1 thì model lặp lại gần đúng câu trả lời sai vừa rồi.
const attempts=(c:Config,retries:number)=>Math.max(1,retries+(c.maxRetries??3)-3);
export async function askJSON<T=any>(c:Config,p:string,t=.3,retries=3,validate?:(x:T)=>void):Promise<T>{const n=attempts(c,retries),temps=[t,.2,.1];let last="",err="";for(let i=1;i<=n;i++){try{last=await askLLM(c,p,{json:true,think:false,temperature:temps[(i-1)%temps.length]});const x=extractJSON<T>(last);if(!x)throw Error("Invalid JSON");validate?.(x);return x}catch(e){err=String(e);console.warn(`[JSON RETRY ${i}/${n}] ${err}`);if(last)console.warn(last.slice(0,1000))}if(i<n)await sleep(backoffMs(i,err))}throw Error(`Failed after ${n} attempts. Last error: ${err}\nLast response:\n${last}`)}
export async function retryLLM(c:Config,p:string,o:any={},retries=3,label="LLM"){const n=attempts(c,retries);let err="";for(let i=1;i<=n;i++){try{const x=await askLLM(c,p,{...o});if(!x.trim())throw Error("Empty response");return x}catch(e){err=String(e);console.warn(`[${label} RETRY ${i}/${n}] ${err}`)}if(i<n)await sleep(backoffMs(i,err))}throw Error(`${label} failed after ${n} attempts. Last error: ${err}`)}
export function validateOutline(x:any,n?:number){if(!x||!Array.isArray(x.chapters)||!x.chapters.length)throw Error("Outline: invalid chapters");if(n&&x.chapters.length!==n)throw Error(`Outline: expected ${n} chapters, got ${x.chapters.length}`);x.chapters.forEach((c:any,i:number)=>{if(typeof c.chapter!=="number")throw Error(`Chapter ${i+1}: invalid chapter`);if(typeof c.title!=="string"||!c.title.trim())throw Error(`Chapter ${i+1}: missing title`)})}
export function validateScenePlan(x:any,n:number){if(!x||!Array.isArray(x.scenes)||x.scenes.length!==n)throw Error(`Scene plan: expected ${n} scenes`);x.scenes.forEach((s:any,i:number)=>{if(s.scene!==i+1)throw Error(`Scene ${i+1}: invalid scene number`);if(typeof s.title!=="string"||!s.title.trim())throw Error(`Scene ${i+1}: missing title`)})}