import type{GenreId,SettingId}from"../types.js";
export const P=(s:string,v:Record<string,string>)=>Object.entries(v).reduce((x,[k,y])=>x.replaceAll(`{{${k}}}`,y),s);
export interface GenrePrompts{id:GenreId;label:string;defaultSetting:SettingId;narration:"first"|"third";defaults?:{durationMinutes:number;chapters:number;scenesPerChapter:number};ARCH:string;OUT:string;SC:string;WR:string;HOOK:string;HOOKFIX:string;FIXSPAN:string;OUTRO:string;MEM:string;EDIT:string;CHECK:string;REVIEW_CH:string;REVIEW_SUM:string;FIXCH:string;FIXVERIFY:string;hookWords:number;outroWords:number;bibleRequired:string[];chapterCriteria:string[];usedMemoryKeys:string[];actsText(chapters:number):string}
export const NO_META=`OUTPUT là văn bản truyện thuần túy. Câu đầu tiên bắt đầu trực tiếp bằng nội dung. TUYỆT ĐỐI KHÔNG viết "Dưới đây là", "Đây là phiên bản", "Sau đây là", "Tôi đã chỉnh sửa". Không Markdown: không #, **, *, _, bullet, code block, blockquote, stage directions, "Narrator:", "Dialogue:", "Scene:", "Chapter:".`;
const WR_HEADING=`QUY TẮC BẮT BUỘC:`;
export const WR_RULES={xungHo:(example:string)=>`XƯNG HÔ: dùng đúng pronounRegister của SCENE. Nếu quan hệ đổi nhiệt ngay trong cảnh thì đổi xưng hô ngay tại câu thoại đó ${example}`,dienKhongGiang:(exception:string)=>`DIỄN, KHÔNG GIẢNG: sau một đoạn kịch tính, TUYỆT ĐỐI KHÔNG thêm câu người kể giải thích ý nghĩa hay tổng kết cảm xúc kiểu "điều đó khiến cô cảm thấy...", "cô nhận ra rằng...", "quả thực...". Để hành động và lời thoại tự nói. Ngoại lệ DUY NHẤT là ${exception}.`,khongLapKetLuan:`KHÔNG LẶP KẾT LUẬN CẢM XÚC: các ý đã dùng rồi được liệt kê trong USED bên dưới. Không được diễn đạt lại bất kỳ ý nào trong đó, kể cả bằng lời khác. Mỗi cảnh chỉ được nêu tối đa MỘT kết luận cảm xúc mới.`,suVieMoi:`SỰ VIỆC MỚI: cảnh phải chứa đúng newIncident của SCENE, xảy ra trực tiếp trên trang chứ không phải được kể lại.`,chiTietViet:`CHI TIẾT BỐI CẢNH CỤ THỂ: dùng signatureProp và các {{SET_DETAIL}} thay cho tính từ chung chung.`,khongTomTatThoiGian:`KHÔNG TÓM TẮT THỜI GIAN: cấm viết "mấy tháng trôi qua", "kỳ nghỉ hè đến", "thời gian sau đó". Nếu phải nhảy thời gian thì mở cảnh bằng một hành động cụ thể đang diễn ra.`,vietChoNguoiNghe:`VIẾT CHO NGƯỜI NGHE: tối đa 3 người có lời thoại trong cảnh; khi hai nhân vật cùng giới cùng xuất hiện thì gọi TÊN thay vì "anh ấy/cô ấy"; số viết bằng chữ; không chơi chữ dựa vào mặt chữ.`,conSoCuThe:`CON SỐ CỤ THỂ: mọi khoản tiền, tuổi tác, giờ giấc, khoảng cách phải là con số cụ thể lấy đúng từ ledger trong BIBLE và timeline trong MEMORY, không được viết "một số tiền lớn", "nhiều năm trước", "khuya lắm rồi". Nếu cảnh phát sinh con số mới thì chọn số lẻ, đời thường (bảy mươi mốt triệu, hai giờ mười lăm) chứ không phải số tròn trịa.`,cauNganChoGiongDoc:`CÂU NGẮN CHO GIỌNG ĐỌC: phần lớn câu dưới 20 chữ. Khi kịch tính lên đỉnh, viết chuỗi câu rất ngắn cùng chủ ngữ ("Bà ngồi xuống. Bà mở tủ. Bà kéo cái hũ ra."). Không viết câu ghép nhiều mệnh đề lồng nhau; người nghe không tua lại được.`,tuDuChu:`TỪ PHẢI ĐỦ CHỮ, DÙNG TỪ LÁY: tiếng Việt đời thường nói bằng từ hai tiếng. Viết "một nét gọn gàng" chứ không phải "một nét gọn", "không trọn vẹn" chứ không phải "không trọn", "giọng dịu dàng" chứ không phải "giọng dịu". Luật CÂU NGẮN CHO GIỌNG ĐỌC nói về CÂU, không nói về TỪ: muốn ngắn thì bỏ mệnh đề thừa, tuyệt đối không cắt cụt ở giữa một từ — cắt như vậy chẳng tiết kiệm được mấy chữ mà nghe như người nước ngoài đang tập nói tiếng Việt. Tả dáng vẻ, cử chỉ và tiếng động thì ưu tiên từ láy đời thường (rón rén, lụi cụi, tần ngần, hớt hải, lẩm bẩm, run rẩy, thủng thẳng) thay cho tính từ trần trụi.`};
export const buildWR=(o:{intro:string;rules:string[];refs:string}):string=>`${o.intro}\n${WR_HEADING}\n${o.rules.map((r,i)=>`${i+1}. ${r}`).join("\n")}\n${NO_META} ${o.refs}`;
const SC_TAIL=`scene CHỈ là số, tên cảnh chỉ nằm trong title. Chỉ JSON {"scenes":[...]}. Không Markdown.`;
export const buildSC=(o:{intro:string;bullets:string[];uniqueRule:string;refs:string}):string=>`${o.intro}\n${o.bullets.map(b=>`- ${b}`).join("\n")}\n${o.uniqueRule} ${SC_TAIL} ${o.refs}`;
const MEM_HEAD=`Cập nhật continuity. Chỉ JSON `,MEM_TAIL=`Không bịa, không Markdown.`;
export const MEM_KEYS_DOC=`important=true nếu chi tiết ảnh hưởng danh tính/bí mật/cốt truyện về sau hoặc là mạch chưa giải quyết; false nếu chỉ là chi tiết bối cảnh/miêu tả thông thường. Bỏ khỏi unresolvedQuestions/foreshadowing những mục đã được giải quyết/trả lời trong SCENE, không giữ lại.`;
export const MEM_BULLETS={usedEmotionalBeats:`usedEmotionalBeats: các kết luận cảm xúc đã nêu trong truyện, mỗi mục 3-6 từ (ví dụ "cô thấy bế tắc", "sống như trong tù"). Gộp mọi cách nói khác nhau của cùng một ý thành MỘT mục duy nhất. Đây là danh sách cấm lặp cho các cảnh sau, phải giữ lại toàn bộ mục cũ.`,motifOccurrences:`motifOccurrences: mỗi lần motif xuất hiện ghi một mục "lần thứ mấy - mang nghĩa gì".`,timeline:`timeline: mọi con số về tuổi và mốc thời gian đã nêu trong truyện, dạng {"tuổi nhân vật":"","đã cưới bao lâu":"","mốc đã trôi qua":""}, để các cảnh sau không mâu thuẫn.`};
export const buildMEM=(o:{schema:string;bullets:string[];refs:string}):string=>`${MEM_HEAD}${o.schema}. ${MEM_KEYS_DOC}\n${o.bullets.map(b=>`- ${b}`).join("\n")}\n${MEM_TAIL} ${o.refs}`;
const EDIT_HEADING=`VIỆC PHẢI LÀM:`,EDIT_TAIL=`Output bắt đầu trực tiếp bằng câu chuyện. Không meta, không Markdown, không "Dưới đây là", "Đây là phiên bản", "Tôi đã chỉnh sửa".`;
export const EDIT_TASKS={xoaLapY:`XÓA LẶP Ý: nếu một kết luận cảm xúc được nói lại nhiều lần dù bằng lời khác, chỉ giữ lần mạnh nhất, xóa hẳn các lần còn lại.`,catGiangGiai:`CẮT GIẢNG GIẢI: xóa các câu người kể giải thích ý nghĩa hoặc tổng kết cảm xúc ngay sau một đoạn đã dựng đủ rõ. NHƯNG GIỮ LẠI các câu báo trước dạng "Bà không biết đó là lần cuối..." — đó là công cụ giữ chân người nghe; chỉ xóa bớt khi trong cùng một cảnh có nhiều hơn một câu như vậy, giữ câu neo vào vật cụ thể nhất.`,xungHo:`XƯNG HÔ: kiểm tra xưng hô nhất quán trong từng cảnh và khớp nhiệt độ quan hệ, chỉ đổi khi quan hệ thực sự đổi.`,timeline:`TIMELINE: sửa mọi con số tuổi hoặc mốc thời gian mâu thuẫn với timeline trong MEMORY, lấy MEMORY làm chuẩn.`,tuDuChu:`TỪ ĐỦ CHỮ: nối lại những từ bị cắt cụt còn một tiếng — "một nét gọn" thành "một nét gọn gàng", "không trọn" thành "không trọn vẹn". Chỗ nào đang dùng tính từ trần trụi để tả dáng vẻ hay cử chỉ thì thay bằng từ láy đời thường (rón rén, tần ngần, lụi cụi, hớt hải). Đây là việc THÊM chữ; không được nhân đó cắt tình tiết cho bù lại độ dài.`,catCauThua:`Cắt câu thừa nhưng KHÔNG cắt tình tiết và KHÔNG rút ngắn quá 15% độ dài bản nháp.`};
export const buildEDIT=(o:{intro:string;tasks:string[];refs:string}):string=>`${o.intro}\n${EDIT_HEADING}\n${o.tasks.map((t,i)=>`${i+1}. ${t}`).join("\n")}\n${EDIT_TAIL} ${o.refs}`;
const FIXCH_FROZEN=`NGUYÊN TẮC BẤT DI BẤT DỊCH: giữ nguyên toàn bộ tình tiết, tên, tuổi, quan hệ, mốc thời gian, con số và diễn biến. Không thêm tình tiết mới, không xoá tình tiết cũ, không đổi kết cục của chương. Chỉ sửa CÁCH KỂ.`,FIXCH_TASK=`VIỆC PHẢI LÀM: đọc từng mục trong ISSUES và sửa đúng chỗ đó theo suggestion. Mỗi issue phải được xử lý, không bỏ sót mục nào. Ngoài các lỗi đã nêu thì đừng viết lại những đoạn đang ổn.`,FIXCH_HEADING=`BẮT BUỘC THÊM:`,FIXCH_TAIL=`Output bắt đầu trực tiếp bằng câu chuyện. Không meta, không Markdown, không "Dưới đây là", không liệt kê những gì đã sửa.`;
export const FIXCH_EXTRAS={cliffhanger:`Câu cuối chương phải là sự kiện vật lý hoặc câu thoại đúng như cliffhanger trong OUTLINE, và KHÔNG được có bất kỳ câu tả cảnh nào sau nó.`,xungHo:`Xưng hô phải đúng quan hệ trong BIBLE và giữ nhất quán suốt chương.`,tiengVietTuNhien:`Mọi câu tiếng Việt phải tự nhiên, đúng nghĩa, đúng chính tả; {{SET_FOREIGN}}.`,tuDuChu:`Từ phải đủ chữ: không để từ bị cắt cụt còn một tiếng ("một nét gọn" phải là "một nét gọn gàng", "không trọn" phải là "không trọn vẹn"), và ưu tiên từ láy đời thường khi tả dáng vẻ hay cử chỉ.`,doDai:`Độ dài bản sửa không được ngắn hơn 85% bản gốc.`};
export const buildFIXCH=(o:{intro:string;extras:string[];refs:string}):string=>`${o.intro}\n${FIXCH_FROZEN}\n${FIXCH_TASK}\n${FIXCH_HEADING}\n${o.extras.map(e=>`- ${e}`).join("\n")}\n${FIXCH_TAIL} ${o.refs}`;
const FIXVERIFY_BODY=`đã xử lý được những lỗi biên tập viên nêu ra hay chưa. Chỉ JSON, không Markdown:\n{"results":[{"index":0,"fixed":true,"evidence":""}],"newProblems":[""]}\nMỗi mục trong ISSUES có index đúng bằng thứ tự của nó trong mảng, phải trả lời đủ mọi mục, không bỏ sót.\nfixed=true chỉ khi lỗi đã hết hẳn trong bản mới; còn sót, sửa nửa vời, hoặc chuyển lỗi sang chỗ khác thì fixed=false. evidence phải trích một đoạn ngắn trong CHƯƠNG SAU KHI SỬA làm bằng chứng, không nói chung chung, không nhắc lại lời của issue.\nnewProblems: tối đa 3 lỗi NGHIÊM TRỌNG mới phát sinh do chính lần sửa này (mâu thuẫn tình tiết, sai tên hoặc tuổi, mất tình tiết cũ, câu văn hỏng nghĩa, xưng hô loạn). Không có thì trả mảng rỗng. Không bịa lỗi.`;
export const buildFIXVERIFY=(o:{subject:string;refs:string}):string=>`Kiểm tra bản sửa của MỘT CHƯƠNG ${o.subject} ${FIXVERIFY_BODY}\n${o.refs}`;
// Tầng chấm điểm trước đây mù hoàn toàn về bối cảnh: nó chỉ đọc thấy "tiếng Việt" trong
// intro rồi tự suy ra người Việt, nên một truyện đặt ở Trung Quốc bị ghi lỗi "thoại thiếu
// tự nhiên so với tâm lý người Việt". Sai đó không dừng ở báo cáo - lượt sửa sau đọc chính
// lời phê ấy làm chỉ thị, tức là bị lệnh kéo truyện về Việt Nam. Cả ba prompt chấm đều
// phải biết chúng đang đọc thế giới nào.
const JUDGE_WORLD=`
BỐI CẢNH TRUYỆN: {{SET_JUDGE}}
`;
const REVIEW_JSON_ONLY=`Chỉ JSON, không Markdown:`,SCORES_SIX_KEYS=`"scores" chỉ được chứa đúng 6 khóa nêu trên, không thêm khóa nào khác.`;
const GRADING_SCALE=`THANG ĐIỂM 0-10: 0-4 hỏng, phải viết lại; 5-6 tạm đọc được nhưng nhạt; 7 đạt chuẩn nghe được; 8 tốt; 9-10 chỉ dành cho đoạn thật sự xuất sắc, rất hiếm khi cho. Chấm thẳng tay, đừng nới điểm. Nếu có issue severity "cao" thì tiêu chí liên quan không được quá 6.`;
const REVIEW_CH_TAIL=`issues: chỉ nêu lỗi có thật, detail phải trích một đoạn ngắn trong chương làm bằng chứng, suggestion phải là việc sửa cụ thể chứ không phải lời khuyên chung chung. Không bịa lỗi, chương sạch thì trả mảng rỗng. Tối đa 6 issue. strengths tối đa 3 mục, mỗi mục một câu.`;
export const buildREVIEW_CH=(o:{intro:string;criteria:[string,string][];outlineCheck:string;refs:string}):string=>`${o.intro}${JUDGE_WORLD}${REVIEW_JSON_ONLY}\n{"chapter":0,"scores":{${o.criteria.map(([k])=>`"${k}":0`).join(",")}},"issues":[{"severity":"cao|vừa|thấp","detail":"","suggestion":""}],"strengths":[""]}\n${SCORES_SIX_KEYS}\n${GRADING_SCALE}\nTỪNG TIÊU CHÍ:\n${o.criteria.map(([k,d])=>`- ${k}: ${d}`).join("\n")}\nĐỐI CHIẾU OUTLINE: ${o.outlineCheck}\n${REVIEW_CH_TAIL}\n${o.refs}`;
const SUM_TOTAL_NOTE=`Truyện có tổng cộng {{TOTAL}} chương và ĐÃ VIẾT XONG. Nếu bảng điểm dưới đây thiếu một vài chương thì đó là do lỗi kỹ thuật lúc chấm, không phải truyện viết thiếu: cứ đánh giá trên các chương có sẵn, không hạ điểm và không kết luận truyện dang dở vì lý do đó.`,SUM_SCALE=`THANG ĐIỂM 0-10 như chấm chương: 7 là đạt chuẩn nghe được, 9-10 rất hiếm khi cho.`;
const SUM_TAIL=`overall: điểm tổng cho cả truyện, KHÔNG phải trung bình cộng máy móc; hạ điểm mạnh nếu một lỗi nghiêm trọng kéo dài qua nhiều chương.\ntopIssues: tối đa 5 mục, gộp lỗi lặp ở nhiều chương thành MỘT mục và liệt kê số chương vào "chapters", ưu tiên lỗi ảnh hưởng cả truyện hơn lỗi cục bộ.
"chapters" phải là SỐ CHƯƠNG THẬT, chép đúng từ trường "chapter" trong bảng điểm dưới đây, nằm trong khoảng 1 đến {{TOTAL}}. TUYỆT ĐỐI KHÔNG dùng vị trí trong mảng và KHÔNG BAO GIỜ ghi 0 — không có chương 0. Mục nào không quy được về chương cụ thể thì để "chapters":[].\nverdict: 3-5 câu, nói thẳng truyện này đã nghe được chưa và việc quan trọng nhất cần sửa là gì.`;
export const buildREVIEW_SUM=(o:{intro:string;criteria:[string,string][];refs:string}):string=>`${o.intro}${JUDGE_WORLD}${SUM_TOTAL_NOTE} ${REVIEW_JSON_ONLY}\n{"scores":{${o.criteria.map(([k])=>`"${k}":0`).join(",")}},"overall":0,"topIssues":[{"severity":"cao|vừa|thấp","chapters":[2,5],"detail":"","suggestion":""}],"verdict":""}\n${SCORES_SIX_KEYS}\n${SUM_SCALE}\n${o.criteria.map(([k,d])=>`- ${k}: ${d}`).join("\n")}\n${SUM_TAIL}\n${o.refs}`;
const CHECK_JSON=`Chỉ JSON {"issues":[{"type":"","severity":"cao|vừa|thấp","detail":"","suggestion":""}],"unresolvedThreads":[],"verdict":""}.`,CHECK_TAIL=`Không bịa lỗi, nếu sạch thì trả mảng rỗng. Không Markdown.`;
export const buildCHECK=(o:{intro:string;types:string;finds:string;refs:string}):string=>`${o.intro}${JUDGE_WORLD}${CHECK_JSON} type chọn trong: ${o.types}. Tìm: ${o.finds}. ${CHECK_TAIL} ${o.refs}`;
const HOOKFIX_FROZEN=`NGUYÊN TẮC BẤT DI BẤT DỊCH: giữ nguyên mọi tình tiết, vai vế, mốc thời gian và con số đã có trong LỜI DẪN CŨ. GIỮ NGUYÊN tên riêng của nhân vật, gia đình, công ty và địa danh, kể cả tên Hán-Việt — đó là bối cảnh của truyện, không phải lỗi dịch. Không thêm tình tiết mới. Không hé lộ thêm bất cứ điều gì bản cũ đang giấu: không nói ra thủ đoạn, không nói ai thật sự đứng sau, không nói cái kết. Chỉ sửa CÁCH NÓI.`;
const PROSE_EASY=`NÓI CHO DỄ HIỂU MÀ VẪN MƯỢT — ĐÂY LÀ VIỆC CHÍNH:
- Từ đời thường trước. Có từ thuần Việt thay được thì đừng dùng từ Hán-Việt văn vẻ: "nghiệt ngã" thành "cay đắng", "an bài" thành "sắp đặt sẵn", "cơ hàn" thành "nghèo".
- Câu dài rối thì VIẾT LẠI CHO GỌN, TUYỆT ĐỐI KHÔNG chặt làm đôi. Mỗi câu phải đứng được một mình, đủ chủ ngữ và vị ngữ. Không để lại mảnh cụt kiểu "Bước vào lễ đường in tên chị." — đó là mẩu vụn, không phải câu.
- Từ phải đủ chữ: rút gọn ở mệnh đề thừa, KHÔNG rút ở giữa một từ. "một nét gọn gàng" chứ không phải "một nét gọn", "không trọn vẹn" chứ không phải "không trọn". Từ láy đời thường (rón rén, tần ngần, lụi cụi, hớt hải) là tiếng Việt dễ nghe chứ không phải chữ hoa mỹ — luật xoá chữ hoa mỹ bên dưới không đụng tới chúng.
- Nhịp phải xen kẽ: câu vừa để kể, câu ngắn để nhấn. Ba bốn câu ngắn liên tiếp nghe như đọc gạch đầu dòng chứ không phải kể chuyện. Nối ý bằng từ nối đời thường (rồi, mà, nhưng, vì, thế là) thay vì chấm câu liên tục.
- Câu quá 25 chữ thường là dấu hiệu rối: gỡ mệnh đề lồng nhau ra, đừng chồng ba ý vào một câu.
- Thay danh từ trừu tượng bằng thứ nhìn thấy được: đừng nói "bi kịch gia đình", hãy nói "mâm cơm không ai đụng đũa".
- Xoá chữ hoa mỹ không thêm thông tin gì: "định mệnh", "trớ trêu thay", "ngậm ngùi", "xót xa thay", "dòng đời xô đẩy".
- Người nghe không tua lại được: phải hiểu ngay lần đầu, nhưng nghe ra là một người đang kể chuyện, không phải một bản tin.`;
const HOOKFIX_TAIL=`Độ dài: khoảng {{WORDS}} từ và TUYỆT ĐỐI không quá {{WORDS}} cộng thêm 15%. Bản cũ dài hơn mức đó thì phải cắt xuống cho vừa — cắt chữ thừa và câu rườm, KHÔNG cắt tình tiết. Chỗ nào bản cũ đã hay thì để yên, đừng viết khác đi cho có. OUTPUT là lời dẫn hoàn chỉnh đã sửa, văn bản thuần, không Markdown, không tiêu đề, không "Dưới đây là", không giải thích đã sửa gì.`;
export const buildHOOKFIX=(o:{intro:string;keep:string[];refs:string}):string=>`${o.intro}\n${HOOKFIX_FROZEN}\n${PROSE_EASY}\nGIỮ ĐÚNG CÔNG THỨC CỦA THỂ LOẠI:\n${o.keep.map(k=>`- ${k}`).join("\n")}\n${HOOKFIX_TAIL} ${o.refs}{{FEEDBACK}}`;
const FIXSPAN_FROZEN=`NGUYÊN TẮC BẤT DI BẤT DỊCH: giữ nguyên tình tiết, tên riêng của nhân vật và địa danh (kể cả tên Hán-Việt — đó là bối cảnh truyện, không phải lỗi), tuổi tác, quan hệ, mốc thời gian và mọi con số. Không thêm tình tiết mới, không xoá tình tiết cũ. Chỉ sửa CÁCH KỂ của đúng những đoạn được đánh dấu.
KHỚP VỚI HAI ĐẦU: đoạn trước và đoạn sau mỗi đoạn bạn sửa sẽ GIỮ NGUYÊN từng chữ. Đoạn bạn viết ra phải nối liền mạch được với chúng — cùng thì, cùng xưng hô, không nhắc lại thứ đoạn trước vừa nói, không bỏ lửng thứ đoạn sau đang chờ.
MỘT ĐỔI MỘT: mỗi đoạn được đánh dấu trả về ĐÚNG MỘT đoạn. Không gộp hai đoạn làm một, không tách một đoạn thành hai, và TUYỆT ĐỐI không có dòng trống bên trong một đoạn.`;
const FIXSPAN_TAIL=`Chỉ JSON, không Markdown, không giải thích:
{"paragraphs":{"3":"nội dung đoạn 3 đã sửa","17":"nội dung đoạn 17 đã sửa"}}
Khoá phải đúng bằng danh sách {{INDEXES}} — không thừa một khoá, không thiếu một khoá. Đoạn nào không có dấu <<<SỬA>>> thì TUYỆT ĐỐI không đưa vào kết quả.`;
export const buildFIXSPAN=(o:{intro:string;extras:string[];refs:string}):string=>`${o.intro}
Bạn nhận CẢ chương đã đánh số đoạn để có đủ ngữ cảnh, nhưng CHỈ những đoạn mang dấu <<<SỬA>>> mới được phép đổi.
${FIXSPAN_FROZEN}
${PROSE_EASY}
QUY TẮC RIÊNG CỦA THỂ LOẠI:
${o.extras.map(e=>`- ${e}`).join("\n")}
${FIXSPAN_TAIL} ${o.refs}`;

// Rút Ý TƯỞNG từ bản ghi lời một video, để pipeline viết một truyện MỚI từ đầu. Prompt này
// là NGƯỜI ĐỌC DUY NHẤT của bản ghi lời: {{TRANSCRIPT}} không xuất hiện ở bất kỳ prompt nào
// khác, nên SC/WR/EDIT không có đường nào nhìn thấy câu chữ của video gốc. Cùng một cốt
// truyện thì hợp lệ, diễn đạt lại lời văn của người khác thì không - và cái sau cũng chính
// là thứ hệ thống bản quyền của YouTube bắt được. check-genre-prompts.ts giữ khẳng định đó.
// Genre-neutral có chủ ý: tiền đề không phụ thuộc thể loại, ARCH mới là chỗ áp thể loại.
export const FIDELITY:Record<string,string>={
loose:`Chỉ viết MỘT đoạn văn xuôi 60-100 chữ, nêu: nhân vật chính là ai, bị đẩy vào tình thế gì, xung đột cốt lõi là gì, và kết thúc theo hướng nào. KHÔNG liệt kê diễn biến, KHÔNG chia mục.`,
frame:`Viết đúng bốn mục dưới đây, mỗi mục bắt đầu một dòng mới:
TIỀN ĐỀ: một đoạn 60-100 chữ nêu nhân vật chính, tình thế và xung đột cốt lõi.
NHÂN VẬT: 3-5 vai, mỗi vai một dòng, ghi vai trò và động cơ trong một câu.
DIỄN BIẾN CHÍNH: 5-8 bước leo thang, mỗi bước một dòng, mỗi dòng nêu MỘT sự việc xảy ra.
CÁI KẾT: 1-2 câu nói rõ chuyện kết thúc ra sao và ai phải trả giá.`,
tight:`Viết đúng năm mục dưới đây, mỗi mục bắt đầu một dòng mới:
TIỀN ĐỀ: một đoạn 60-100 chữ nêu nhân vật chính, tình thế và xung đột cốt lõi.
NHÂN VẬT: 3-5 vai, mỗi vai một dòng, ghi vai trò và động cơ trong một câu.
DIỄN BIẾN CHÍNH: 5-8 bước leo thang, mỗi bước một dòng, mỗi dòng nêu MỘT sự việc xảy ra.
DIỄN BIẾN CHI TIẾT: 10-14 mốc theo đúng trình tự trong bản ghi, mỗi mốc một dòng, mỗi dòng một câu ngắn nêu SỰ VIỆC xảy ra.
CÁI KẾT: 1-2 câu nói rõ chuyện kết thúc ra sao và ai phải trả giá.`};
export const IDEA=`Đọc bản ghi lời của một truyện audio dưới đây và rút ra Ý TƯỞNG để người khác viết một truyện MỚI.
THỨ BẠN LẤY là cốt truyện, tình thế và quan hệ nhân vật. THỨ BẠN BỎ LẠI là lời văn: TUYỆT ĐỐI KHÔNG chép câu nào trong bản ghi, KHÔNG trích dẫn, KHÔNG diễn đạt lại từng câu một. Lời văn sẽ do người khác viết mới hoàn toàn.
KHÔNG dùng tên riêng xuất hiện trong bản ghi. Gọi nhân vật bằng vai (người mẹ, đứa con trai, cô con dâu, người quản lý) — truyện mới sẽ có dàn nhân vật và tên riêng của chính nó.
Nếu bản ghi có câu chào kênh, lời cảm ơn, quảng cáo hay kêu gọi đăng ký, bỏ qua hết, chúng không thuộc về câu chuyện.
{{FIDELITY}}
Viết bằng tiếng Việt. OUTPUT là văn bản thuần, không Markdown, không tiêu đề, không "Dưới đây là", không lời bình về bản ghi.
BẢN GHI LỜI:
{{TRANSCRIPT}}`;
