import type{SettingId}from"../types.js";
export interface SettingPack{id:SettingId;label:string;names:string;detail:string;prop:string;proverb:string;foreign:string;judge:string}
const VIETNAM:SettingPack={id:"vietnam",label:`Việt Nam`,names:`Nhân vật mang tên Việt Nam (Hoa, Tuấn, bà Sáu, ông Bảy, chị Lài). Địa danh, tiền tệ (đồng), chức danh và thủ tục hành chính đều của Việt Nam.`,detail:`chi tiết đời sống Việt Nam có tên gọi cụ thể (món ăn, vật dụng, địa danh, thủ tục hành chính, chức danh)`,prop:`đạo cụ đời thường Việt Nam cụ thể được cầm, dùng hoặc làm hỏng trong cảnh (cái điếu cày, chậu nước lá, xe đạp điện, cuốn sổ nợ, phích nước, mâm cơm nguội)`,proverb:`Một câu tục ngữ hoặc định kiến quen thuộc của người Việt về chủ đề truyện`,foreign:`xoá sạch từ nước ngoài, chữ Hán, và các câu vô nghĩa kiểu dịch máy nếu gặp`,judge:`Truyện lấy bối cảnh Việt Nam. Chấm lời thoại theo cách người Việt nói chuyện thật ngoài đời.`};
const CHINA:SettingPack={id:"china",label:`Trung Quốc`,names:`Nhân vật mang tên Trung Quốc đọc theo âm Hán-Việt (Tần Dịch Thâm, Tô Duyệt, Lục Thiếu Khanh, Diệp Thanh Hoà) — họ trước tên sau. KHÔNG dùng tên Việt Nam, KHÔNG dùng bính âm La-tinh. Tên công ty dạng "tập đoàn Tần Thị". Địa danh, món ăn, chức danh và thủ tục đều của Trung Quốc và đều gọi bằng âm Hán-Việt quen thuộc với người nghe Việt. Tiền tệ tính bằng tệ.`,detail:`chi tiết đời sống Trung Quốc hiện đại có tên gọi cụ thể (món ăn, vật dụng, địa danh, chức danh, thủ tục)`,prop:`đạo cụ đời thường Trung Quốc hiện đại cụ thể được cầm, dùng hoặc làm hỏng trong cảnh (ấm trà tử sa, hộp cơm giữ nhiệt, thẻ ra vào công ty, phong bao đỏ, chiếc ô gấp trong cốp xe)`,proverb:`Một câu tục ngữ hoặc thành ngữ Trung Quốc quen thuộc, dịch sang tiếng Việt, về chủ đề truyện`,foreign:`GIỮ NGUYÊN tên riêng Hán-Việt của nhân vật, công ty và địa danh — đó là bối cảnh Trung Quốc, không phải lỗi dịch. Chỉ xoá chữ Hán nguyên khối, từ tiếng Anh, bính âm La-tinh, và các câu vô nghĩa kiểu dịch máy`,judge:`Truyện lấy bối cảnh Trung Quốc, kể bằng tiếng Việt cho người Việt nghe. Chấm lời thoại theo cách người Trung Quốc trong hoàn cảnh đó nói chuyện, diễn đạt bằng tiếng Việt tự nhiên. TUYỆT ĐỐI KHÔNG trừ điểm, KHÔNG ghi thành lỗi chỉ vì nhân vật không cư xử như người Việt, không theo phong tục Việt Nam, hay mang tên Hán-Việt — đó là bối cảnh đã chọn, không phải lỗi. Ngôn ngữ là tiếng Việt; thế giới thì không.`};
// Biến DUY NHẤT đi vào tầng chấm điểm, và nó phải đảo ngược ở bối cảnh Trung Quốc y hệt
// `foreign`. Không có nó, prompt chấm chỉ thấy chữ "tiếng Việt" rồi tự suy ra người Việt:
// một truyện đặt ở Trung Quốc bị trừ điểm vì "thoại thiếu tự nhiên so với tâm lý người
// Việt" - chấm sai bối cảnh mà chính người dùng đã chọn, rồi lượt sửa sau sẽ dựa vào lời
// phê đó mà kéo truyện về Việt Nam.
export const SETTINGS:Record<SettingId,SettingPack>={vietnam:VIETNAM,china:CHINA};
export const SETTINGS_LIST:{id:SettingId|"auto";label:string}[]=[{id:"auto",label:"Theo thể loại"},{id:"vietnam",label:VIETNAM.label},{id:"china",label:CHINA.label}];
export const settingVars=(id:SettingId)=>{const s=SETTINGS[id]??SETTINGS.vietnam;return{SET_NAMES:s.names,SET_DETAIL:s.detail,SET_PROP:s.prop,SET_PROVERB:s.proverb,SET_FOREIGN:s.foreign,SET_JUDGE:s.judge}};
